@startuml

header Discover Student Loans
footer Discover - TruCreds Hackathon - Team Activiti Ninjas

title Ecosystem Setup

autonumber 1
skinparam noteBorderColor black

actor "John Doe \n (Student)" as STUDENT #lightblue
actor "Mike Doe \n (Cosigner)" as COSIGNER #99FF99
participant "John Doe\nDigitial Wallet" as SWALLET #lightblue
participant "Mike Doe\n Digital Wallet" as CWALLET #99FF99
participant "Discover" as DFS #orange
participant "DMV" as DMV
participant "IRS" as IRS
participant "SSN\nOffice" as SSN
participant "Passport\nOffice" as PASSPORT
participant "Dept of\nDefense" as MILITARY
participant "University" as UNIVERSITY #yellow
participant "Public\nRegistry" as REGISTRY #pink

group Onboard Stakeholders 
DFS->REGISTRY: Register Public DID
DMV->REGISTRY: Register Public DID
IRS->REGISTRY: Register Public DID
SSN->REGISTRY: Register Public DID
PASSPORT->REGISTRY: Register Public DID
MILITARY->REGISTRY: Register Public DID
UNIVERSITY->REGISTRY: Register Public DID
end

group Register Schemas and Claim Definitions
DMV->REGISTRY: Register Digital DL Schema
DMV->REGISTRY: Register Credential Definition for Digital DL Certification using Digital DL Schema
IRS->REGISTRY: Register W2 Schema
IRS->REGISTRY: Register Credential Definition for Digital W2 Certification using Digital W2 Schema
SSN->REGISTRY: Register Digital SSN Schema
SSN->REGISTRY: Register Credential Definition for Digital SSN Certification using Digital SSN Schema
PASSPORT->REGISTRY: Register Digital Passport Schema
PASSPORT->REGISTRY: Register Credential Definition for Digital Passport Certification using Digital Passport Schema
MILITARY->REGISTRY: Register Digital Military ID Schema
MILITARY->REGISTRY: Register Credential Definition for Digital Military Duty Certification using Digital Military Schema
UNIVERSITY->REGISTRY: Register Digital University Schema
UNIVERSITY->REGISTRY: Register Credential Definition for Digital Student ID Certification using Digital University Schema
end

group Digital DL Issuance   
STUDENT->SWALLET: Request Digital DL Certification
SWALLET<->REGISTRY: Digital DL Certification
SWALLET->STUDENT: Issue Digital DL Certification

COSIGNER->CWALLET: Request Digital DL Certification
CWALLET<->REGISTRY: Digital DL Certification
CWALLET->COSIGNER: Issue Digital DL Certification
end

group Digital W2 Issuance   
STUDENT->SWALLET: Request Digital W2 Certification
SWALLET<->REGISTRY: Digital W2 Certification
SWALLET->STUDENT: Issue Digital W2 Certification

COSIGNER->CWALLET: Request Digital W2 Certification
CWALLET<->REGISTRY: Digital W2 Certification
CWALLET->COSIGNER: Issue Digital W2 Certification
end

group Digital SSN Issuance   
STUDENT->SWALLET: Request Digital SSN Certification
SWALLET<->REGISTRY: Digital SSN Certification
SWALLET->STUDENT: Issue Digital SSN Certification

COSIGNER->CWALLET: Request Digital SSN Certification
CWALLET<->REGISTRY: Digital SSN Certification
CWALLET->COSIGNER: Issue Digital SSN Certification
end

group Digital Passport Issuance   
STUDENT->SWALLET: Request Digital Passport Certification
SWALLET<->REGISTRY: Digital Passport Certification
SWALLET->STUDENT: Issue Digital Passport Certification

COSIGNER->CWALLET: Request Digital Passport Certification
CWALLET<->REGISTRY: Digital Passport Certification
CWALLET->COSIGNER: Issue Digital Passport Certification
end

group Digital Military ID Issuance   
STUDENT->SWALLET: Request Digital Military ID Certification
SWALLET<->REGISTRY: Digital Military ID Certification
SWALLET->STUDENT: Issue Digital Military ID Certification

COSIGNER->CWALLET: Request Digital Military ID Certification
CWALLET<->REGISTRY: Digital Military ID Certification
CWALLET->COSIGNER: Issue Digital Military ID Certification
end

group Digital Student ID Issuance   
STUDENT->SWALLET: Request Digital Student ID Certification
SWALLET<->REGISTRY: Digital Student ID Certification
SWALLET->STUDENT: Issue Digital Student ID Certification
end

@enduml
