@startuml

header Discover Student Loans
footer Discover - TruCreds Hackathon - Team Activiti Ninjas

title Student Loan Application

autonumber 1
skinparam noteBorderColor black

actor "John Doe \n (Student)" as STUDENT #lightblue
actor "Mike Doe \n (Cosigner)" as COSIGNER #99FF99
participant "John Doe\nDigitial Wallet" as SWALLET #lightblue
participant "Mike Doe\n Digital Wallet" as CWALLET #99FF99
participant "Discover" as DFS #orange
participant "Discover Bank API" as DFSAPI #orange
participant "DMV" as DMV
participant "IRS" as IRS
participant "SSN\nOffice" as SSN
participant "Passport\nOffice" as PASSPORT
participant "Dept of\nDefense" as MILITARY
participant "University" as UNIVERSITY #yellow
participant "Public\nRegistry" as REGISTRY #pink

group Apply for Student Loan
STUDENT->DFS: Apply for Student Loan
DFS->DFS: Generate QR Code
STUDENT->SWALLET: Scan QR Code
SWALLET->DFS: Scan QR Code
DFS->REGISTRY: Verify credentials 
REGISTRY->DFS: Verify credentials 
DFS->DFSAPI: Process Loan Application
note over DFSAPI: Military member benefits\nare applied here.
DFSAPI->DFS: LoanAppID and CoSignerKey
DFS->STUDENT: Loan Status and CoSignerKey
end

@enduml
