require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://cdn.cocoapods.org/'
source 'https://gitlab.com/evernym/mobile/mobile-sdk.git'

platform :ios, '12.0'

target 'MsdkProject' do
  config = use_native_modules!
  pod 'vcx', '0.0.233'
  use_frameworks!
  $RNFirebaseAsStaticFramework = true
  pod 'apptentive-ios'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # react-native-permissions permission handlers
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID/Permission-FaceID.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone/Permission-Microphone.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"

  target 'MsdkProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  pre_install do |installer|
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

      installer.pod_targets.each do |pod|
          if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
              def pod.build_type;
                  # Uncomment the line corresponding to your CocoaPods version
                  Pod::BuildType.static_library # >= 1.9
                  # Pod::Target::BuildType.static_library # < 1.9
              end
          end
      end
  end
  
  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      if ['iProov', 'Socket.IO-Client-Swift', 'Starscream'].include? target.name
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
     end

  end

end
